# Custom Language File for Launcher Customizer

[ejs.app]
title = "Omega Launcher - v1.0 (Beta)"

[ejs.landing]
mediaGitHubURL = "https://www.omegamc.it"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.omegamc.it"

[ejs.settings]
sourceGithubLink = "https://discord.omegamc.it"
supportLink = "https://discord.omegamc.it"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU OMEGA LAUNCHER"
welcomeDescription = ""
welcomeDescCTA = "Copyright © 2026 Razor® Studios"
